development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ricar
  pool: 5
  username: ricar
  password: ricar
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ricar
  pool: 5
  username: ricar
  password: ricar
  host: localhost




